package model

import "github.com/illacloud/builder-backend/src/utils/resourcelist"

var actionDefaultTutorialMaps = map[int]string{
	resourcelist.TYPE_TRANSFORMER_ID:             "https://TYPE_TRANSFORMER_ID.com/tutorial.mp4",
	resourcelist.TYPE_RESTAPI_ID:                 "https://TYPE_RESTAPI_ID.com/tutorial.mp4",
	resourcelist.TYPE_GRAPHQL_ID:                 "https://TYPE_GRAPHQL_ID.com/tutorial.mp4",
	resourcelist.TYPE_REDIS_ID:                   "https://TYPE_REDIS_ID.com/tutorial.mp4",
	resourcelist.TYPE_MYSQL_ID:                   "https://TYPE_MYSQL_ID.com/tutorial.mp4",
	resourcelist.TYPE_MARIADB_ID:                 "https://TYPE_MARIADB_ID.com/tutorial.mp4",
	resourcelist.TYPE_POSTGRESQL_ID:              "https://TYPE_POSTGRESQL_ID.com/tutorial.mp4",
	resourcelist.TYPE_MONGODB_ID:                 "https://TYPE_MONGODB_ID.com/tutorial.mp4",
	resourcelist.TYPE_TIDB_ID:                    "https://TYPE_TIDB_ID.com/tutorial.mp4",
	resourcelist.TYPE_ELASTICSEARCH_ID:           "https://TYPE_ELASTICSEARCH_ID.com/tutorial.mp4",
	resourcelist.TYPE_S3_ID:                      "https://TYPE_S3_ID.com/tutorial.mp4",
	resourcelist.TYPE_SMTP_ID:                    "https://TYPE_SMTP_ID.com/tutorial.mp4",
	resourcelist.TYPE_SUPABASEDB_ID:              "https://TYPE_SUPABASEDB_ID.com/tutorial.mp4",
	resourcelist.TYPE_FIREBASE_ID:                "https://TYPE_FIREBASE_ID.com/tutorial.mp4",
	resourcelist.TYPE_CLICKHOUSE_ID:              "https://TYPE_CLICKHOUSE_ID.com/tutorial.mp4",
	resourcelist.TYPE_MSSQL_ID:                   "https://TYPE_MSSQL_ID.com/tutorial.mp4",
	resourcelist.TYPE_HUGGINGFACE_ID:             "https://TYPE_HUGGINGFACE_ID.com/tutorial.mp4",
	resourcelist.TYPE_DYNAMODB_ID:                "https://TYPE_DYNAMODB_ID.com/tutorial.mp4",
	resourcelist.TYPE_SNOWFLAKE_ID:               "https://TYPE_SNOWFLAKE_ID.com/tutorial.mp4",
	resourcelist.TYPE_COUCHDB_ID:                 "https://TYPE_COUCHDB_ID.com/tutorial.mp4",
	resourcelist.TYPE_HFENDPOINT_ID:              "https://TYPE_HFENDPOINT_ID.com/tutorial.mp4",
	resourcelist.TYPE_ORACLE_ID:                  "https://TYPE_ORACLE_ID.com/tutorial.mp4",
	resourcelist.TYPE_APPWRITE_ID:                "https://TYPE_APPWRITE_ID.com/tutorial.mp4",
	resourcelist.TYPE_GOOGLESHEETS_ID:            "https://TYPE_GOOGLESHEETS_ID.com/tutorial.mp4",
	resourcelist.TYPE_NEON_ID:                    "https://TYPE_NEON_ID.com/tutorial.mp4",
	resourcelist.TYPE_UPSTASH_ID:                 "https://TYPE_UPSTASH_ID.com/tutorial.mp4",
	resourcelist.TYPE_AIRTABLE_ID:                "https://TYPE_AIRTABLE_ID.com/tutorial.mp4",
	resourcelist.TYPE_HYDRA_ID:                   "https://TYPE_HYDRA_ID.com/tutorial.mp4",
	resourcelist.TYPE_AI_AGENT_ID:                "https://TYPE_AI_AGENT_ID.com/tutorial.mp4",
	resourcelist.TYPE_ORACLE_9I_ID:               "https://TYPE_ORACLE_9I_ID.com/tutorial.mp4",
	resourcelist.TYPE_ILLA_DRIVE_ID:              "https://TYPE_ILLA_DRIVE_ID.com/tutorial.mp4",
	resourcelist.TYPE_TRIGGER_ID:                 "https://TYPE_TRIGGER_ID.com/tutorial.mp4",
	resourcelist.TYPE_SERVER_SIDE_TRANSFORMER_ID: "https://TYPE_SERVER_SIDE_TRANSFORMER_ID.com/tutorial.mp4",
}
