package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/illacloud/builder-backend/internal/idconvertor"
	"github.com/illacloud/builder-backend/internal/repository"
)

type AppDtoForExport struct {
	ID              string                        `json:"appId"` // generated by database primary key serial
	UID             uuid.UUID                     `json:"uid"`
	TeamID          string                        `json:"teamID"`
	Name            string                        `json:"appName" validate:"required"`
	ReleaseVersion  int                           `json:"releaseVersion"`  // release version used for mark the app release version.
	MainlineVersion int                           `json:"mainlineVersion"` // mainline version keep the newest app version in database.
	Config          *repository.AppConfig         `json:"config"`
	CreatedBy       string                        `json:"-" `
	CreatedAt       time.Time                     `json:"-"`
	UpdatedBy       string                        `json:"updatedBy"`
	UpdatedAt       time.Time                     `json:"updatedAt"`
	AppActivity     AppActivity                   `json:"appActivity"`
	EditedBy        []*repository.UserForEditedBy `json:"editedBy"`
}

func NewAppDtoForExport(a *AppDto, usersLT map[int]*repository.User) *AppDtoForExport {
	// construct edited by
	editedByUsers := make([]*repository.UserForEditedBy, len(a.EditedBy))
	for _, appEditedBy := range a.EditedBy {
		userID := appEditedBy.UserID
		user, hit := usersLT[userID]
		if !hit {
			continue
		}
		editedByUser := repository.NewUserForEditedBy(user, appEditedBy.EditedAt)
		editedByUsers = append(editedByUsers, editedByUser)
	}
	// feedback
	return &AppDtoForExport{
		ID:              idconvertor.ConvertIntToString(a.ID),
		UID:             a.UID,
		TeamID:          idconvertor.ConvertIntToString(a.TeamID),
		Name:            a.Name,
		ReleaseVersion:  a.ReleaseVersion,
		MainlineVersion: a.MainlineVersion,
		Config:          a.Config,
		CreatedBy:       idconvertor.ConvertIntToString(a.CreatedBy),
		CreatedAt:       a.CreatedAt,
		UpdatedBy:       idconvertor.ConvertIntToString(a.UpdatedBy),
		UpdatedAt:       a.UpdatedAt,
		AppActivity:     a.AppActivity,
		EditedBy:        editedByUsers,
	}
}

func (resp *AppDtoForExport) ExportForFeedback() interface{} {
	return resp
}
