package illacapacity

const (
	TRANSACTION_SERIAL_MODIFY_TARGET_CAPACITY_VOLUME  = 1
	TRANSACTION_SERIAL_MODIFY_TARGET_CAPACITY_BALANCE = 2
)

const (
	TRANSACTION_SERIAL_MODIFY_METHOD_NONE   = 0
	TRANSACTION_SERIAL_MODIFY_METHOD_CREATE = 1
	TRANSACTION_SERIAL_MODIFY_METHOD_UPDATE = 2
	TRANSACTION_SERIAL_MODIFY_METHOD_DELETE = 3
	TRANSACTION_SERIAL_MODIFY_METHOD_ADD    = 4
	TRANSACTION_SERIAL_MODIFY_METHOD_DEDUCT = 5
)
