// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/illa-family/builder-backend/api/resthandler"
	"github.com/illa-family/builder-backend/api/router"
	repository2 "github.com/illa-family/builder-backend/internal/repository"
	"github.com/illa-family/builder-backend/internal/util"
	"github.com/illa-family/builder-backend/pkg/action"
	"github.com/illa-family/builder-backend/pkg/app"
	"github.com/illa-family/builder-backend/pkg/db"
	"github.com/illa-family/builder-backend/pkg/resource"
	"github.com/illa-family/builder-backend/pkg/smtp"
	"github.com/illa-family/builder-backend/pkg/user"
	"github.com/illa-family/builder-backend/pkg/user/repository"
)

// Injectors from wire.go:

func Initialize() (*Server, error) {
	config, err := GetAppConfig()
	if err != nil {
		return nil, err
	}
	engine := gin.New()
	sugaredLogger := util.NewSugardLogger()
	dbConfig, err := db.GetConfig()
	if err != nil {
		return nil, err
	}
	gormDB, err := db.NewDbConnection(dbConfig, sugaredLogger)
	if err != nil {
		return nil, err
	}
	userRepositoryImpl := repository.NewUserRepositoryImpl(gormDB, sugaredLogger)
	smtpConfig, err := smtp.GetConfig()
	if err != nil {
		return nil, err
	}
	smtpServer := smtp.NewSMTPServer(smtpConfig)
	userServiceImpl := user.NewUserServiceImpl(userRepositoryImpl, sugaredLogger, smtpServer)
	userRestHandlerImpl := resthandler.NewUserRestHandlerImpl(sugaredLogger, userServiceImpl)
	userRouterImpl := router.NewUserRouterImpl(userRestHandlerImpl)
	appRepositoryImpl := repository2.NewAppRepositoryImpl(sugaredLogger, gormDB)
	appVersionRepositoryImpl := repository2.NewAppVersionRepositoryImpl(sugaredLogger, gormDB)
	appServiceImpl := app.NewAppServiceImpl(sugaredLogger, appRepositoryImpl, appVersionRepositoryImpl)
	appRestHandlerImpl := resthandler.NewAppRestHandlerImpl(sugaredLogger, appServiceImpl)
	appRouterImpl := router.NewAppRouterImpl(appRestHandlerImpl)
	actionRepositoryImpl := repository2.NewActionRepositoryImpl(sugaredLogger, gormDB)
	resourceRepositoryImpl := repository2.NewResourceRepositoryImpl(sugaredLogger, gormDB)
	actionServiceImpl := action.NewActionServiceImpl(sugaredLogger, actionRepositoryImpl, resourceRepositoryImpl)
	actionRestHandlerImpl := resthandler.NewActionRestHandlerImpl(sugaredLogger, actionServiceImpl)
	actionRouterImpl := router.NewActionRouterImpl(actionRestHandlerImpl)
	resourceServiceImpl := resource.NewResourceServiceImpl(sugaredLogger, resourceRepositoryImpl)
	resourceRestHandlerImpl := resthandler.NewResourceRestHandlerImpl(sugaredLogger, resourceServiceImpl)
	resourceRouterImpl := router.NewResourceRouterImpl(resourceRestHandlerImpl)
	restRouter := router.NewRESTRouter(sugaredLogger, userRouterImpl, appRouterImpl, actionRouterImpl, resourceRouterImpl)
	server := NewServer(config, engine, restRouter, sugaredLogger)
	return server, nil
}
