package operationlist

const SIGNAL_PING = 0
const SIGNAL_ENTER = 1
const SIGNAL_LEAVE = 2
const SIGNAL_CREATE_STATE = 3
const SIGNAL_DELETE_STATE = 4
const SIGNAL_UPDATE_STATE = 5
const SIGNAL_MOVE_STATE = 6
const SIGNAL_CREATE_OR_UPDATE_STATE = 7
const SIGNAL_BROADCAST_ONLY = 8
const SIGNAL_PUT_STATE = 9
const SIGNAL_GLOBAL_BROADCAST_ONLY = 10
const SIGNAL_COOPERATE_ATTACH = 11
const SIGNAL_COOPERATE_DISATTACH = 12
const SIGNAL_MOVE_CURSOR = 13
const SIGNAL_FORCE_REFRESH = 14
const SIGNAL_TAKE_APP_SNAPSHOT = 15
const SIGNAL_RECOVER_APP_SNAPSHOT = 16
const SIGNAL_RUN = 17
const SIGNAL_STOP_RUN = 18
const SIGNAL_CLEAN_CHAT_HISTTORY = 19
